language: php
matrix:
  include:
    - php: 7.4
      env: NEOS_TRAVISCI=travis:phpunit
    - php: hhvm
      env: NEOS_TRAVISCI=travis:phpunit
  allow_failures:
    - php: 7.4
    - php: hhvm
  fast_finish: true

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev